name: opencv2023
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.12.7=h5b45459_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - debugpy=1.5.1=py310hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - importlib-metadata=6.1.0=pyha770c72_0
  - importlib_metadata=6.1.0=hd8ed1ab_0
  - ipykernel=6.15.0=pyh025b116_0
  - ipython=8.11.0=pyh08f2357_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=8.1.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py310h5588dad_0
  - libffi=3.4.2=hd77b12b_6
  - libsodium=1.0.18=h8d14728_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openssl=1.1.1t=h2bbff1b_0
  - packaging=23.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.0.1=py310haa95532_0
  - platformdirs=3.1.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - python=3.10.9=h966fe2a_2
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pywin32=305=py310h2bbff1b_0
  - pyzmq=23.2.0=py310hd77b12b_0
  - setuptools=65.6.3=py310haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.1=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.2=py310he2412df_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2022g=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py310haa95532_0
  - wincertstore=0.2=py310haa95532_2
  - xz=5.2.10=h8cc25b3_1
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
    - numpy==1.24.2
    - opencv-python==4.7.0.72
prefix: C:\Users\Home\anaconda3\envs\opencv2023
